(ns mcp-tasks.generated-workflows
  "Auto-generated prompt lists for GraalVM native image compatibility.
  
  Generated by dev/build.clj:generate-prompt-manifest during build.
  Do not edit manually - regenerate with: clojure -T:build generate-prompt-manifest")

(def builtin-workflows
  "Vector of built-in workflow prompt names (without .md extension)."
  ["complete-story" "create-story-pr" "create-story-tasks" "execute-story-child" "execute-task" "refine-task" "review-story-implementation"])

(def builtin-categories
  "Set of built-in category prompt names (without .md extension)."
  #{"bugfix" "medium" "large" "clarify-task" "simple"})
